name: Release Assets Upload

on:
  release:
    types: [created]  # срабатывает только при создании нового релиза

jobs:
  upload-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.3

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build Windows
        run: make bld_win64

      - name: Build macOS
        run: make bld_macos

      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/win64/k8s-prf-win64.zip
          asset_name: k8s-prf-win64.zip
          asset_content_type: application/zip

      - name: Upload macOS asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/darwin/k8s-prf-darwin.zip
          asset_name: k8s-prf-darwin.zip
          asset_content_type: application/zip
